language: python

before_install:
  # set up awscli packages
  - pip install awscli

script:
  - ls -lAF

deploy:
  provider: script
  script: bash aws s3 sync ./site s3://$S3_BUCKET/ --delete --acl private --cache-control "max-age=2592000" 

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html /index.css
