env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  # set up awscli packages
  - pip install --user awscli

script: aws s3 sync ./site s3://$S3_BUCKET/ --delete --acl private --cache-control "max-age=2592000"
